# -*- coding: utf-8 -*-
"""motor_novela.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q0dqbW47TaZDPf18XV6BVB8rUbwrLVQz
"""

# motor_novela.py
# Motor reutilizable de scraping + traducción de novelas web

import os
import time
import re
import requests
from bs4 import BeautifulSoup
from deep_translator import GoogleTranslator


def ejecutar_motor(NOVELA_CONFIG):
    """
    Ejecuta el scraping y traducción de una novela usando navegación NEXTURL.
    Devuelve un dict con información del resultado.
    """

    # =========================
    # Inicialización
    # =========================
    translator = GoogleTranslator(
        source=NOVELA_CONFIG.get("IDIOMA_ORIGEN", "auto"),
        target=NOVELA_CONFIG["IDIOMA_DESTINO"]
    )

    def contiene_chino(texto):
        return bool(re.search(r'[\u4e00-\u9fff]', texto))

    def traducir_bloque_robusto(texto, max_retries=3):
        for _ in range(max_retries):
            try:
                if not texto.strip():
                    return ""
                traduccion = translator.translate(texto)
                if contiene_chino(traduccion):
                    raise Exception("Traducción inválida")
                return traduccion
            except Exception:
                time.sleep(1.2)
        return texto  # fallback seguro

    def obtener_html(url):
        try:
            headers = {
                "User-Agent": (
                    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) "
                    "Chrome/120.0.0.0 Safari/537.36"
                ),
                "Referer": NOVELA_CONFIG["URL_LIBRO"]
            }
            r = requests.get(url, headers=headers, timeout=20)
            r.encoding = NOVELA_CONFIG["ENCODING"]
            return r.text if r.status_code == 200 else None
        except Exception:
            return None

    def extraer_datos(html, num_cap):
        soup = BeautifulSoup(html, "html.parser")

        # Título
        h1 = soup.select_one(NOVELA_CONFIG["SELECTORES"]["TITULO"])
        titulo_orig = h1.get_text(strip=True) if h1 else f"Capítulo {num_cap}"
        titulo_es = traducir_bloque_robusto(titulo_orig)

        # Contenido
        cont = soup.select_one(NOVELA_CONFIG["SELECTORES"]["CONTENIDO"])
        if not cont:
            return titulo_es, ""

        for basura in cont.select("div.gadBlock, div.adBlock, script, ins, iframe"):
            basura.decompose()

        texto = ""
        for p in cont.find_all("p"):
            linea = p.get_text(strip=True)
            if len(linea) < 2:
                continue
            texto += traducir_bloque_robusto(linea) + "\n\n"
            time.sleep(NOVELA_CONFIG["ESPERA_TRAD"])

        return titulo_es, texto

    # =========================
    # Proceso principal
    # =========================
    os.makedirs(NOVELA_CONFIG["CARPETA_SALIDA"], exist_ok=True)

    texto_volumen = f"NOVELA: {NOVELA_CONFIG['NOMBRE']}\n\n"

    url_actual = NOVELA_CONFIG["URL_INICIAL"]
    contador = 0

    while url_actual:
        contador += 1

        html = obtener_html(url_actual)
        if not html:
            break

        titulo, contenido = extraer_datos(html, contador)

        texto_volumen += (
            f"\n\n{'='*40}\n{titulo}\n{'='*40}\n\n{contenido}\n"
        )

        # Extraer nextUrl
        soup = BeautifulSoup(html, "html.parser")
        script = soup.find("script", string=lambda s: s and "nextUrl" in s)

        next_url = None
        if script:
            match = re.search(r"nextUrl\s*=\s*'([^']+)'", script.string)
            if match:
                next_url = NOVELA_CONFIG["DOMINIO"] + match.group(1)

        if not next_url:
            break

        if (
            NOVELA_CONFIG["CANTIDAD_CAPITULOS"] is not None
            and contador >= NOVELA_CONFIG["CANTIDAD_CAPITULOS"]
        ):
            break

        url_actual = next_url
        time.sleep(NOVELA_CONFIG["ESPERA_REQUEST"])

    # =========================
    # Guardado
    # =========================
    cap_inicio = 1
    cap_final = contador

    nombre_archivo = (
        f"{NOVELA_CONFIG['NOMBRE']}_"
        f"Caps_{cap_inicio}_a_{cap_final}.txt"
    )

    ruta_final = os.path.join(
        NOVELA_CONFIG["CARPETA_SALIDA"],
        nombre_archivo
    )

    with open(ruta_final, "w", encoding="utf-8") as f:
        f.write(texto_volumen)

    return {
        "estado": "ok",
        "capitulos_procesados": contador,
        "archivo": nombre_archivo,
        "ruta": ruta_final
    }